=head1 NAME

MinorImpact::Manual::Installation

=head1 DESCRIPTION

=head2 Examples

=head3 RedHat/CentOS

=head4 ...from git

 $ git clone https://github.com/minorimpact/perl-minorimpact.git
 $ export PERL5LIB=$PERL5LIB:$PWD/perl-minorimpact
 $ yum -y install epel-release

=head4 ...from prebuilt packages

Add the Minor Impact repository information to /etc/yum.repos.d/minorimpact.repo:

  [minorimpact]
    name=Minor Impact Tools/Libraries
    baseurl=https://minorimpact.com/repo
    enabled=1
    gpgcheck=1
    gpgkey=https://minorimpact.com/RPM-GPG-KEY-minorimpact

Install the package:

  $ yum -y install epel-release perl-MinorImpact

=head3 Database Configuration

Set up a database to use, if you don't already have one.  Included are basic instructions for installing a mysql database here, just for testing purposes.

  # yum install mariadb-server
  # systemctl mariadb start
  # mysql -e 'create database minorimpact;'
  # mysql -e "CREATE USER 'minorimpact'@'localhost' IDENTIFIED BY 'minorimpact';"
  # mysql -e "CREATE USER 'minorimpact'@'%' IDENTIFIED BY 'minorimpact';"
  # mysql -e "GRANT ALL PRIVILEGES ON minorimpact.* to 'minorimpact'@'localhost';"
  # mysql -e "GRANT ALL PRIVILEGES ON minorimpact.* to 'minorimpact'@'%';"

=head3 Configuration File

Create /etc/minorimpact.conf, if it doesn't already exist, and add the following database connection information:

  db:
    database = minorimpact
    db_host = localhost
    db_port = 3306
    db_user = minorimpact
    db_password = minorimpact

See L<MinorImpact::Manual::Configuration|MinorImpact::Manual::Configuration> for more configuration options.

=head1 AUTHOR

Patrick Gillan <pgillan@minorimpact.com>

=cut
